ToDoListApp/Models/ErrorViewModel.cs
using System;

namespace ToDoListApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ToDoListApp/Models/Quest.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ToDoListApp.Models
{
    public class Quest
    {
        public int ID { get; set; }
        public string QuestName { get; set; }
        public bool isImportant { get; set; }
        public bool isDone { get; set; }
    }
}

ToDoListApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ToDoListApp.Models;

namespace ToDoListApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ToDoListApp/Controllers/QuestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ToDoListApp.Data;
using ToDoListApp.Models;

namespace ToDoListApp.Controllers
{

    public class QuestController : Controller
    {
        private readonly ToDoContext _context;

        public QuestController(ToDoContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View(_context.Quests.ToList());
        }
    
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Quest quest = _context.Quests.SingleOrDefault(x => x.ID == id);
            if (quest == null)
            {
                return NotFound();
            }

            _context.Remove(quest);
            _context.SaveChanges();

            TempData["message"] = "Person deleted";
            return RedirectToAction("Index");
        }



        [HttpPost]
        public IActionResult Add(string add)
        {
            if (add != null)
            { 
                Quest quest = new Quest { QuestName = add, isDone = false, isImportant = false };
                _context.Add(quest);
                _context.SaveChanges();

                return RedirectToAction("Index");
            } else
            {
                return RedirectToAction("Index");

            }
        }
        public IActionResult Important(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Quest quest = _context.Quests.SingleOrDefault(x => x.ID == id);
            if (quest == null)
            {
                return NotFound();
            }
            if (quest.isImportant == true)
            {
                quest.isImportant = false;
                _context.SaveChanges();
            } else
            {
                quest.isImportant = true;
                _context.SaveChanges();
            }
            TempData["state"] = 0;
            return RedirectToAction("Index");
        }

        public IActionResult Done(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Quest quest = _context.Quests.SingleOrDefault(x => x.ID == id);
            if (quest == null)
            {
                return NotFound();
            }
            if (quest.isDone == true)
            {
                quest.isDone = false;
                _context.SaveChanges();
            }
            else
            {
                quest.isDone = true;
                _context.SaveChanges();
            }
            TempData["state"] = 0;
            return RedirectToAction("Index");
        }
        public IActionResult All()
        {
            TempData["state"] = 0;
            return RedirectToAction("Index");
        }
        public IActionResult doneList()
        {
            TempData["state"] = 2;
            return RedirectToAction("Index");
        }
        public IActionResult Active()
        {
            TempData["state"] = 1;
            return RedirectToAction("Index");
        }
        public IActionResult SearchBtn(string search)
        {
            if (search != null)
            {
                TempData["stringToSearch"] = search;
                TempData["state"] = 3;
                return RedirectToAction("Index");
            } else
            {
                return RedirectToAction("Index");
            }

        }
    }
}

ToDoListApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home page";
    //Layout = null;
}

<head>
    <link rel="icon" href="~/images/checklist.png" type="image/x-icon" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>

</head>

<body>
    <h1>Welcome to Quest log</h1>
    <p>Dealing with routine tasks by completing Quest</p>
    <p>Solving everyday tasks is going to be your epic reward and achievment</p>
    <div class="thumbnail">
        <img src="~/images/AdventureTime.jpg" alt="Adventure Time" style="width:100%"/>
    </div>
</body>

ToDoListApp/Views/Quest/Index.cshtml
@model IEnumerable<ToDoListApp.Models.Quest>

@{
    ViewData["Title"] = " Quest Log";
    int taskNum = 0;
    int taskDone = 0;
    
}

<head>
    <link rel="icon" href="~/images/checklist.png" type="image/x-icon" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>

</head>

@foreach (var item in Model)
{
    taskNum += 1;
    if (item.isDone == true)
    {
        taskDone += 1;
    }
}

<div class="row">
    <div class="col-sm-6"><h1>Quest Log</h1></div>
    <div class="col-sm-6"><h3>@taskNum to do, @taskDone done</h3></div>
</div>

<form asp-controller="Quest" asp-action="SearchBtn" method="post">
    <div class="col-sm-6">
        <input type="text" class="form-control" placeholder="Type to search" name="search">
    </div>
    <div class="col-sm-6">
        <input type="submit" class="btn btn-success" value="Search">
    </div>
</form>

    <br />
    <br />




    @{
        switch (TempData["state"])
        {
            case 0:
                Html.RenderPartial("_QuestList");
                break;
            case 1:
                Html.RenderPartial("_ActiveList");
                break;
            case 2:
                Html.RenderPartial("_DoneList");
                break;
            case 3:
                Html.RenderPartial("_SearchList");
                break;
            default:
                Html.RenderPartial("_QuestList");
                break;
        }

    }

    <form asp-controller="Quest" asp-action="Add" method="post">
        <div class="col-sm-6">
            <input type="text" class="form-control" placeholder="What needs to be done?" name="add">
        </div>
        <div class="col-sm-6">
            <input type="submit" class="btn btn-success" value="Add">
        </div>
    </form>
    <br />
    <br />

ToDoListApp/Views/Quest/_ActiveList.cshtml
@model IEnumerable<ToDoListApp.Models.Quest>

<table class="table">
    <thead>
        <tr>
            <th>
                <h3>Quest Name</h3>
            </th>
            <th>
                <div class="btn-group" id="grpBtn">
                    <a asp-action="All" type="button" class="btn btn-default" id="All">All</a>
                    <a asp-action="Active" type="button" class="btn btn-default" id="Active">Active</a>
                    <a asp-action="doneList" type="button" class="btn btn-default" id="Done">Done</a>
                </div>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            if (item.isDone != true)
            {
                <tr>
                    <td>
                        @if (item.isDone == true && item.isImportant == true)
                        {
                            <b>
                                <s>
                                    @item.QuestName
                                </s>
                            </b>
                        }
                        else if (item.isImportant == true && item.isDone == false)
                        {
                            <b>
                                @item.QuestName
                            </b>
                        }
                        else if (item.isDone == true && item.isImportant == false)
                        {
                            <s>
                                @item.QuestName
                            </s>
                        }
                        else
                        {
                            @item.QuestName
                        }
                    </td>
                    <td>
                        <a asp-action="Important" asp-route-id="@item.ID" class="btn btn-primary">
                            <img src="~/images/chat.png" />
                        </a>
                        <a asp-action="Done" asp-route-id="@item.ID" class="btn btn-success">
                            <img src="~/images/correct.png" />
                        </a>
                        <a asp-action="Delete" asp-route-id="@item.ID" class="btn btn-danger">
                            <img src="~/images/trash.png" />
                        </a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

ToDoListApp/Views/Quest/_DoneList.cshtml
@model IEnumerable<ToDoListApp.Models.Quest>

<table class="table">
    <thead>
        <tr>
            <th>
                <h3>Quest Name</h3>
            </th>
            <th>
                <div class="btn-group" id="grpBtn">
                    <a asp-action="All" type="button" class="btn btn-default" id="All">All</a>
                    <a asp-action="Active" type="button" class="btn btn-default" id="Active">Active</a>
                    <a asp-action="doneList" type="button" class="btn btn-default" id="Done">Done</a>
                </div>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            if (item.isDone == true)
            {
                <tr>
                    <td>
                        @if (item.isDone == true && item.isImportant == true)
                        {
                            <b>
                                <s>
                                    @item.QuestName
                                </s>
                            </b>
                        }
                        else if (item.isImportant == true && item.isDone == false)
                        {
                            <b>
                                @item.QuestName
                            </b>
                        }
                        else if (item.isDone == true && item.isImportant == false)
                        {
                            <s>
                                @item.QuestName
                            </s>
                        }
                        else
                        {
                            @item.QuestName
                        }
                    </td>
                    <td>
                        <a asp-action="Important" asp-route-id="@item.ID" class="btn btn-primary">
                            <img src="~/images/chat.png" />
                        </a>
                        <a asp-action="Done" asp-route-id="@item.ID" class="btn btn-success">
                            <img src="~/images/correct.png" />
                        </a>
                        <a asp-action="Delete" asp-route-id="@item.ID" class="btn btn-danger">
                            <img src="~/images/trash.png" />
                        </a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

ToDoListApp/Views/Quest/_QuestList.cshtml
@model IEnumerable<ToDoListApp.Models.Quest>

<table class="table">
    <thead>
        <tr>
            <th>
                <h3>Quest Name</h3>
            </th>
            <th>
                <div class="btn-group" id="grpBtn">
                    <a asp-action="All" type="button" class="btn btn-default" id="All">All</a>
                    <a asp-action="Active" type="button" class="btn btn-default" id="Active">Active</a>
                    <a asp-action="doneList" type="button" class="btn btn-default" id="Done">Done</a>
                </div>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
         {
            <tr>
                <td>
                    @if (item.isDone == true && item.isImportant == true)
                     {
                        <b>
                            <s>
                                @item.QuestName
                            </s>
                        </b>
                     }
                     else if (item.isImportant == true && item.isDone == false)
                     {
                        <b>
                            @item.QuestName
                        </b>
                     }
                     else if (item.isDone == true && item.isImportant == false)
                     {
                        <s>
                            @item.QuestName
                        </s>
                     }
                     else
                     {
                        @item.QuestName
                     }
                </td>
                <td>
                    <a asp-action="Important" asp-route-id="@item.ID" class="btn btn-primary">
                        <img src="~/images/chat.png" />
                    </a>
                    <a asp-action="Done" asp-route-id="@item.ID" class="btn btn-success">
                        <img src="~/images/correct.png" />
                    </a>
                    <a asp-action="Delete" asp-route-id="@item.ID" class="btn btn-danger">
                        <img src="~/images/trash.png" />
                    </a>
                </td>
           </tr>
         }
    </tbody>
</table>

ToDoListApp/Views/Quest/_SearchList.cshtml
@model IEnumerable<ToDoListApp.Models.Quest>

<table class="table">
    <thead>
        <tr>
            <th>
                <h3>Quest Name</h3>
            </th>
            <th>
                <div class="btn-group" id="grpBtn">
                    <a asp-action="All" type="button" class="btn btn-default" id="All">All</a>
                    <a asp-action="Active" type="button" class="btn btn-default" id="Active">Active</a>
                    <a asp-action="doneList" type="button" class="btn btn-default" id="Done">Done</a>
                </div>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            if (item.QuestName.ToLower() == TempData["stringToSearch"].ToString().ToLower())
            {
                <tr>
                    <td>
                        @if (item.isDone == true && item.isImportant == true)
                        {
                            <b>
                                <s>
                                    @item.QuestName
                                </s>
                            </b>
                        }
                        else if (item.isImportant == true && item.isDone == false)
                        {
                            <b>
                                @item.QuestName
                            </b>
                        }
                        else if (item.isDone == true && item.isImportant == false)
                        {
                            <s>
                                @item.QuestName
                            </s>
                        }
                        else
                        {
                            @item.QuestName
                        }
                    </td>
                    <td>
                        <a asp-action="Important" asp-route-id="@item.ID" class="btn btn-primary">
                            <img src="~/images/chat.png" />
                        </a>
                        <a asp-action="Done" asp-route-id="@item.ID" class="btn btn-success">
                            <img src="~/images/correct.png" />
                        </a>
                        <a asp-action="Delete" asp-route-id="@item.ID" class="btn btn-danger">
                            <img src="~/images/trash.png" />
                        </a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

ToDoListApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ToDoListApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Quest" asp-action="Index">Quest Log</a></li>

                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - Vladimir Titov ASP.Net Course Project</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>